alphaNumber="$(sed -n 's/\("version": "[0-9]\+\.[0-9]\+\.[0-9]\+\-alpha\.\)\([0-9]\+\)\("\)\(,\)/\2/p' package.json)"

previousCommit="$(git log -1 --pretty=%B)"

# If we have an alphaNumber on the package.json, we'll remove it
if [ "$alphaNumber" != "" ]; 
    then
        sed -i 's/\("version": "[0-9]\+\.[0-9]\+\.[0-9]\+\)\(-alpha\.\)\([0-9]\+\)\("\)/\1\4/' package.json
fi

# If previous commit was generated by bump-package-version.sh (identified by *autobump* on the commit message)
# We add the changes and ammend them to the previous commit
if [[ "$previousCommit" == *"autobump"* ]];
    then
        git add package.json
        git commit --amend --no-edit
        git push
fi