alphaTag="$(sed -n 's/\("version": "[0-9]\+\.[0-9]\+\.[0-9]\+\-alpha\.\)\([0-9]\+\)\("\)\(,\)/\2/p' package.json)"
echo "alphaTag: ${alphaTag}"

previousCommit="$(git log -1 --pretty=%B)"
echo "previousCommit: ${previousCommit}"

# If we have an alphaTag on the package.json, we'll remove it
if [ "$alphaTag" != "" ]; 
    then
        sed -i 's/\("version": "[0-9]\+\.[0-9]\+\.[0-9]\+\)\(-alpha\.\)\([0-9]\+\)\("\)/\1\4/' package.json
fi

# If previous commit was generated by bump-package-version.sh (identified by "Version autobumped to"* on the commit message)
# We add the changes and ammend them to the previous commit
if [[ "$previousCommit" == "Version autobumped to"* ]];
    then
        git add package.json
        git commit --amend --no-edit
        git push
fi
